### ISSUE TITLE
IntellIJ Plugin, cannot scroll on Chat

### ISSUE THREAD

**Issue by aaiyer** [TabbyML/tabby#3564]
**Describe the bug**
In the IntelliJ plugin, I am unable to scroll up and down in the Tabby Chat window.

**Information about your version**
Tabby Version - 0.21.1
IntelliJ Plugin Version - 1.9.0
IntelliJ IDE - RustRover 2024.3

**Comment by wsxiaoys** [comment]
Hi - could you also provide a screen recording?

**Comment by aaiyer** [comment]
https://github.com/user-attachments/assets/3c398903-31f7-48f7-aa2d-d82301aeaa61

Attached is a screen recording. I am unable to scroll even with the mouse scroll button or trackpad scrolling.

I forgot to mention, this only happens when I add a snippet by selecting a chunk of code and pressing Ctrl-L to add to Tabby chat.

**Comment by vimasig** [comment]
I have this same issue but a little worse. I always have this issue no matter if I choose a specific chunk of code or not. Only way I can scroll is by selecting using left click, and then moving cursor up/down until it gets out of IDE.

**Tabby version** 0.25.2
**Plugin version** 1.11.0
**IntelliJ version** 2024.3.4

**Comment by icycodes** [comment]
I can reproduce this issue on Linux. It appears to be related to use of the JCEF browser off-screen-rendering on Linux.

**Comment by icycodes** [comment]
To avoid triggering this bug, make sure not to use the mouse wheel while the focus is on the input box in the chat panel. Instead, only use the mouse wheel when the focus is on the chat conversation area.
If the issue has already occurred, you can try focusing on the chat conversation area and using the up/down arrow keys to scroll through the chat. Alternatively, restarting the IDE should resolve the problem.

My guess is that this issue might be caused by the mouse wheel event being sent to the wrong component in the webview. Once the wheel event is sent to a specific component, it cannot be sent to another.

**Comment by dannyxu2015** [comment]
- same issue in MacOS 15.4.1 , idea 2025.1.1.1 ultimate edition: can not scroll at all, no matter mouse focus on input box or chat conversation area
- could not input Chinese in input box, but can answer in Chinese

**Comment by nailujx86** [comment]
This is still an issue. Scrolling in other JCEF WebViews does not cause any problems.

**Comment by IonutLupu00** [comment]
I am encountering this issue as well. Using up/down arrows and page up/page down works as a workaround, but having the precision and quickness of mouse wheel scrolling is preferable.
